### ISSUE TITLE
Finalize one of the modes

### ISSUE THREAD

**Issue by rankoliang** [rankoliang/Dino-War#2]
We need the mechanics and design of a mode figured out. A flow chart or decision tree would be great.

We would need to know:
- [x] all of the different ways the user can interact with the game
- [x] the feedback a user receives after interacting (animations, ui elements changing, ect.)
- [ ] how the game state changes after user input
- [ ] what the game end state and conditions look like
- [ ] the essential elements and information we would show to the user (the dinosaurs on each side, score?, level number?)

**Comment by rankoliang** [comment]
Added a design page on the discord

**Comment by timjacksonm** [comment]
wrote out pseudo code in discord for different ways user interacts with the game / animations.

**Comment by timjacksonm** [comment]
Additional challenges to finalize game logic

- [x] Write out Game rules to be used on homepage
- [x] Plan out 10 static game levels
- [ ] Decide on how to incorporate different difficulty settings
- [x] Figure out how we can add non static levels that are randomized.
