### ISSUE TITLE
Feature: Add post battle screen

### ISSUE THREAD

**Issue by rankoliang** [rankoliang/Dino-War#21]
Add a screen when a player clicks the battle button. It should show ui elements for the points that the user guesses and the current count of the points.

**Comment by timjacksonm** [comment]
Just adding some goal checkpoints.

- [x] Post battle screen that shows ui elements for the points that the user guesses and the current count of the points.
- [x] Store score data that can be used in results component.
- [x] Animations! Anything you want. Ideas to think about : Dinos lunge at each other pokemon style / Brawl cloud appears / Translate X movement etc.
