### ISSUE TITLE
Hard Level Values

### ISSUE THREAD

**Issue by timjacksonm** [rankoliang/Dino-War#26]
Hard difficulty includes a new dino type that is a skeleton. These skeletons currently are set to a negative value similar to subtraction. The negative value can sometimes be to much resulting in the answer being a negative number. With how the inputs work you can't type in a negative number.

Suggestion: Update dinos to be higher values 'double digits' or reduce the value of the skeleton dinos.

**Comment by rankoliang** [comment]
We can also update the min values of the input/score to be negative as well.

**Comment by rankoliang** [comment]
I updated the minimum and maximum values of the input now so that they can be negative now!

**Comment by timjacksonm** [comment]
issue was fixed with the merge of adding post-battle-screen.
